### PR TITLE
Rewoked under v0.6.x

### PR DESCRIPTION
**Pull request by cquiroz**
This PR will track progress towards unifying versions 0.3.x and 0.5.x

### CODE REVIEW

**Comment by hrj** [comment]
@cquiroz Thanks for your work on this. This PR is mentioned in a scala-native issue as a requirement before we can use `java.time` from `scala-java-time`. Is that still true? Is there some way I can quickly try out a beta version of this, even if it is not fully stable? I just want to get a quick estimate of the run-time performance of my project when compiled to native, and `java.time` seems to be the only blocker.

**Comment by cquiroz** [comment]
Hi
Sorry, this is still not usable, i’m Making big changes to the whole lib to (among other things) support scala-native but I’m not there yet

**Comment by cquiroz** [comment]
This PR is now ready for review/merge
It accomplish the following:
* Merges the 0.3.x and 0.5.x branches
* Uses sbt-locales to produce the locales db
* Updates best practices using scalafmt, gh actions and sbt-tpolecat

**Comment by sideeffffect** [comment]
:tada:

**Pull request merged**
