### PR TITLE
Add data for and implement getISO3Language

### LINKED ISSUE #116: Implement Locale#getISO3Language
`Locale#getISO3Language` is on the [TODO list](https://github.com/cquiroz/scala-java-locales/blob/08862e46941a976d70140878f2d6812cc8cca977/core/src/main/scala/java/util/Locale.scala#L567). Would be nice to have it.

I would gladly have a go at implementing this but I couldn’t find any obvious source for the data within the CLDR. There is a list available [here](http://loc.gov/standards/iso639-2/ascii_8bits.html). Could/should it perhaps be added as a data source alongside the CLDR?

### PR DESCRIPTION
**Pull request by liff**
Fixes #116.

The data was acquired from [loc.gov](http://www.loc.gov/standards/iso639-2/langhome.html) (under “Code list for downloading”).

The website responds with 403 when attempting to download using `URL#openStream` so I just added the file as-is. The data is not [very frequently updated](http://www.loc.gov/standards/iso639-2/php/code_changes.php) so I suppose it’s ok to just include it in the repo?

### CODE REVIEW

**Comment by cquiroz** [comment]
Hi

Thanks for the PR. I don't want to include data in the deliverables, which doesn't seem the approach is bad but we need to refine it a bit. I'll add suggestions in the code

**Comment by cquiroz** [comment]
I revisited this and the data is not included in the jar, the build prevents that. So the PR seems fine
Is the data not available in CLDR?

**Comment by liff** [comment]
Apologies for the radio silence. From what I can tell there seems to be some connection between the [language aliases](https://unicode.org/cldr/charts/latest/supplemental/aliases.html) that are marked overlong and ISO-639.2 but I don’t know what exactly is going on with that. Apart from those I could not find any explicit list, like that on the Library of Congress, in the CLDR.

FWIW, [`twitter_cldr`](https://github.com/twitter/twitter-cldr-rb/blob/e6eda8001d160c5c5bd6b307b66e2f9c2a141dfb/lib/twitter_cldr/resources/language_codes_importer.rb) uses tables from [sil.org](https://iso639-3.sil.org/) that has both 639-2 and 639-3.

[icu4c](https://github.com/unicode-org/icu/blob/c3abe48e1ce31f5bf073c5dd853ac6a826b83927/icu4c/source/common/uloc.cpp#L68), on the other hand uses hardcoded tables generated by some generator program but web searches did not turn up anything more about the generator.

**Comment by cquiroz** [comment]
Thanks, I think this approach is fine. I merged it to get a 2.13.0 release out of the door

**Pull request merged**
