### PR TITLE
Add test case for Norwegian date formatting supposed to demonstrate #54

### PR DESCRIPTION
**Pull request by mkotsbak**
I'm not sure if this is correct, at least the parameters "Locale.ROOT, cldr21 = true", but it seems to fail at the right place.

### CODE REVIEW

**Comment by cquiroz** [comment]
In this particular test `Locale.ROOT` is ignored and `cldr21` is used to separate the jvm and js versions given that they use different CLDR versions. Most likely you want cldr21=false

According to the cldr file the formats should be:
```.xml
				<dateFormats>
					<dateFormatLength type="full">
						<dateFormat>
							<pattern>EEEE d. MMMM y</pattern>
						</dateFormat>
					</dateFormatLength>
					<dateFormatLength type="long">
						<dateFormat>
							<pattern>d. MMMM y</pattern>
						</dateFormat>
					</dateFormatLength>
					<dateFormatLength type="medium">
						<dateFormat>
							<pattern>d. MMM y</pattern>
						</dateFormat>
					</dateFormatLength>
					<dateFormatLength type="short">
						<dateFormat>
							<pattern>dd.MM.y</pattern>
						</dateFormat>
					</dateFormatLength>
				</dateFormats>
				<timeFormats>
					<timeFormatLength type="full">
						<timeFormat>
							<pattern>HH.mm.ss zzzz</pattern>
							<pattern alt="variant">HH:mm:ss zzzz</pattern>
						</timeFormat>
					</timeFormatLength>
					<timeFormatLength type="long">
						<timeFormat>
							<pattern>HH.mm.ss z</pattern>
							<pattern alt="variant">HH:mm:ss z</pattern>
						</timeFormat>
					</timeFormatLength>
					<timeFormatLength type="medium">
						<timeFormat>
							<pattern>HH.mm.ss</pattern>
							<pattern alt="variant">HH:mm:ss</pattern>
						</timeFormat>
					</timeFormatLength>
					<timeFormatLength type="short">
						<timeFormat>
							<pattern>HH.mm</pattern>
							<pattern alt="variant">HH:mm</pattern>
						</timeFormat>
					</timeFormatLength>
				</timeFormats>
```

**Comment by mkotsbak** [comment]
Ok, I updated the test case according to that data, but it still fails:

```
[error] Test testsuite.javalib.text.DateFormatTest.test_extra_locales failed: org.junit.ComparisonFailure: expected:<[EEEE, d. MMMM ]y> but was:<[y MMMM d, EEE]y>, took 0.124999936 sec
[error]     at <jscode>.$c_Lorg_junit_ComparisonFailure.$c_jl_Throwable.fillInStackTrace__jl_Throwable(/home/marius/projects/scala/sjs/scala-java-locales/testSuite/js/target/scala-2.11/scala-java-locales-testsuite-on-js-test-fastopt.js:27027)
[error]     at <jscode>.$c_Lorg_junit_ComparisonFailure.$c_jl_Throwable.init___T__jl_Throwable(/home/marius/projects/scala/sjs/scala-java-locales/testSuite/js/target/scala-2.11/scala-java-locales-testsuite-on-js-test-fastopt.js:27126)
```

**Comment by cquiroz** [comment]
I fixed how this should be, please check https://github.com/cquiroz/scala-java-locales/commit/16b8598bf86faa64d8cf80da43e66b9c72d8f898

Can you update your PR so we can have this test permanently?

**Comment by cquiroz** [comment]
Thanks for the PR

**Pull request merged**
