### PR TITLE
Implement Locale#getISO3Country

### PR DESCRIPTION
**Pull request by liff**
The alpha-3 codes are taken from `supplementalData.xml / codeMappings / territoryCodes`. As far as I can tell, that is the correct source?

The codes are added as a map to `metadata` but another way would perhaps be to include the alpha-3s directly in the `LDML` entries. Let me know what you think.

### CODE REVIEW

**Comment by cquiroz** [comment]
This is great thanks. Could you point this to the v0.3.x branch?

**Comment by liff** [comment]
Retargeted.

**Comment by cquiroz** [comment]
travis is complaining about style, Could you run scalastyle to verify it?

**Comment by liff** [comment]
Oops, fixed.

**Pull request merged**
