### PR TITLE
Run with -Xmx6G

### PR DESCRIPTION
**Pull request by sideeffffect**
Publishing seems to have failed because of lack of RAM
https://github.com/cquiroz/scala-java-locales/runs/6478760883?check_suite_focus=true#step%3A8%3A596=

### CODE REVIEW

**Review by cquiroz — APPROVED** [review]
Thanks, I guess we need another tag after this is merged

**Comment by sideeffffect** [comment]
Yes.
Btw, I can't see the previous tag (`1.4.0-RC1`)available either :shrug: 
https://repo1.maven.org/maven2/io/github/cquiroz/scala-java-locales_native0.4_2.13/
I guess publishing hasn't been working for some time already

**Comment by sideeffffect** [comment]
we can merge this now :tada:

**Comment by cquiroz** [comment]
Wow, this was quite a fight

**Review by cquiroz — APPROVED** [review]
LGTM

**Comment by sideeffffect** [comment]
We would need a new tag to publish current `master`

**Pull request merged**
